@startuml
actor User
control OrderController
participant OrderService
database Orders
database contact
database OrderTPInfo

User -> OrderController: "/order/create": post
OrderController -> OrderService: createOrder()
OrderService -> Orders: saveOrder()
Orders -> contact: saveContact()
Orders -> OrderTPInfo: saveOrderTPInfo()
OrderService -> User: orderCreated(orderId)

@enduml